# Generated by Django 3.2 on 2021-04-23 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 20, 1, 6, 604337, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 20, 1, 6, 651211, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.user')),
            ],
        ),
    ]
