# Generated by Django 3.2 on 2021-04-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='section_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framaw.sectioncategory'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='section_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framaw.sectionstatus'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='status_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framaw.statusdata'),
        ),
    ]
