# Generated by Django 3.2 on 2021-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0002_auto_20210425_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
