# Generated by Django 3.2 on 2021-04-23 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0002_auto_20210423_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 20, 1, 28, 737138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 20, 1, 28, 690250, tzinfo=utc)),
        ),
    ]
