# Generated by Django 3.2 on 2021-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0003_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='data',
            field=models.TextField(),
        ),
    ]
