# Generated by Django 3.2 on 2021-04-23 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0003_auto_20210423_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
