# Generated by Django 3.2 on 2021-04-23 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0004_auto_20210423_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.file')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='framaw.directory'),
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('valid', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.filesection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.user')),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('valid', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.filesection')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('valid', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.filesection')),
            ],
        ),
        migrations.AddField(
            model_name='filesection',
            name='section_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.sectioncategory'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='section_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.sectionstatus'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='status_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.statusdata'),
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framaw.directory'),
        ),
    ]
