# Generated by Django 3.2 on 2021-04-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0006_auto_20210424_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='framaw.directory'),
        ),
    ]
