# Generated by Django 3.2 on 2021-04-23 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0007_alter_directory_parent_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
