# Generated by Django 3.2 on 2021-04-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framaw', '0008_alter_file_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
